import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

/**
 * GET /api/matrix/auth/linkedin/callback
 *
 * LinkedIn OAuth2 callback — exchanges authorization code for access token.
 * Automatically writes LINKEDIN_USER_ACCESS_TOKEN to .env.local (local dev).
 * On Vercel, displays the token for manual copy.
 */

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const code = searchParams.get("code");
  const error = searchParams.get("error");

  if (error) {
    return new Response(
      `<html><body style="background:#060b12;color:#c9d1d9;font-family:monospace;padding:40px"><h1 style="color:#e84e4c">LinkedIn Auth Failed</h1><p>Error: ${error}</p><p>Description: ${searchParams.get("error_description") || "N/A"}</p><a href="/" style="color:#58a6ff">← Return</a></body></html>`,
      { headers: { "Content-Type": "text/html" } },
    );
  }

  if (!code) {
    return NextResponse.json({ error: "No authorization code received" }, { status: 400 });
  }

  const clientId = process.env.LINKEDIN_CLIENT_ID;
  const clientSecret = process.env.LINKEDIN_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    return NextResponse.json(
      { error: "LINKEDIN_CLIENT_ID or LINKEDIN_CLIENT_SECRET missing" },
      { status: 500 },
    );
  }

  const baseUrl = process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "http://localhost:3000";

  const redirectUri = `${baseUrl}/api/matrix/auth/linkedin/callback`;

  // Exchange code for access token
  let accessToken = "";
  let tokenError = "";

  try {
    const tokenParams = new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri,
      client_id: clientId,
      client_secret: clientSecret,
    });
    const tokenRes = await fetch("https://www.linkedin.com/oauth/v2/accessToken", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: tokenParams.toString() as unknown as BodyInit,
    });

    if (!tokenRes.ok) {
      const errText = await tokenRes.text();
      tokenError = `LinkedIn token exchange failed: ${tokenRes.status} — ${errText.slice(0, 200)}`;
      console.error("[linkedin/callback]", tokenError);
    } else {
      const tokenData = (await tokenRes.json()) as { access_token?: string };
      accessToken = tokenData.access_token || "";
    }
  } catch (e) {
    tokenError = `Network error: ${e instanceof Error ? e.message : "Unknown"}`;
    console.error("[linkedin/callback]", tokenError);
  }

  // ── Try to write to .env.local (local dev only) ──
  let saved = false;
  if (accessToken) {
    try {
      const envPath = path.join(process.cwd(), ".env.local");
      let envContent = "";
      if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, "utf8");
      }
      // Replace or append LINKEDIN_USER_ACCESS_TOKEN
      if (envContent.includes("LINKEDIN_USER_ACCESS_TOKEN=")) {
        envContent = envContent.replace(
          /LINKEDIN_USER_ACCESS_TOKEN=.*/g,
          `LINKEDIN_USER_ACCESS_TOKEN=${accessToken}`,
        );
      } else {
        envContent += `\n# LinkedIn OAuth2 User Token (auto-generated by Matrix auth flow)\nLINKEDIN_USER_ACCESS_TOKEN=${accessToken}\n`;
      }
      fs.writeFileSync(envPath, envContent, "utf8");
      saved = true;
    } catch {
      // Vercel / read-only filesystem — can't write
    }
  }

  // ── Render result page ──
  const tokenDisplay = accessToken
    ? `${accessToken.slice(0, 8)}...${accessToken.slice(-8)}`
    : "NONE";

  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><title>LinkedIn Auth — MyShape Matrix</title>
<style>
  body { background:#060b12; color:#c9d1d9; font-family:system-ui,sans-serif; padding:40px; max-width:600px; margin:0 auto; }
  h1 { color:${accessToken ? "#3fb950" : "#e84e4c"}; font-weight:200; letter-spacing:.08em; }
  .card { border:1px solid #1a2a3a; border-radius:8px; padding:20px; background:#0d1520; margin:16px 0; }
  .token { font-family:monospace; background:#02040a; padding:12px; border-radius:4px; word-break:break-all; font-size:11px; color:#58a6ff; }
  .badge { display:inline-block; padding:4px 12px; border-radius:3px; font-size:10px; letter-spacing:.1em; }
  .ok { background:rgba(63,185,80,.15); color:#3fb950; border:1px solid rgba(63,185,80,.3); }
  .err { background:rgba(232,78,76,.15); color:#e84e4c; border:1px solid rgba(232,78,76,.3); }
  a { color:#58a6ff; }
</style></head>
<body>
<h1>${accessToken ? "✅ LinkedIn Authorized" : "❌ Authorization Failed"}</h1>

<div class="card">
  <p><span class="badge ${accessToken ? "ok" : "err"}">${accessToken ? "TOKEN_ACQUIRED" : "TOKEN_FAILED"}</span></p>
  ${accessToken ? `<p>Token: <span class="token">${tokenDisplay}</span></p>` : ""}
  ${tokenError ? `<p style="color:#e84e4c;font-size:12px">${tokenError.replace(/</g,"&lt;").replace(/>/g,"&gt;")}</p>` : ""}
  <p style="font-size:11px;color:#6e7681;margin-top:16px">
    ${saved ? "✅ Token auto-saved to .env.local as LINKEDIN_USER_ACCESS_TOKEN" : "⚠ Could not auto-save to .env.local. Set LINKEDIN_USER_ACCESS_TOKEN manually in Vercel dashboard → Environment Variables."}
  </p>
</div>

<div class="card">
  <h3 style="font-weight:200;color:#8b949e">Next Steps</h3>
  <ol style="color:#6e7681;font-size:12px;line-height:1.8">
    <li>Restart dev server: <code style="color:#58a6ff">npm run dev</code></li>
    <li>Run Matrix Cruiser: <code style="color:#58a6ff">node scripts/matrix-bot/cruise.js</code></li>
    <li>Dashboard → LinkedIn card → API Push → sent!</li>
  </ol>
</div>

<a href="/" style="font-size:11px">← Return to MyShape</a>
</body></html>`;

  return new Response(html, { headers: { "Content-Type": "text/html" } });
}
