// ═══════════════════════════════════════════════════════════════════
// MyShape Protocol SDK — Public Types
// ═══════════════════════════════════════════════════════════════════

/** SDK configuration */
export interface MyShapeConfig {
  /** Your MyShape API key (starts with ms_live_ or ms_test_) */
  apiKey: string;
  /** Base URL for the MyShape API (default: https://api.myshape.com) */
  baseUrl?: string;
}

/** 3D keypoint in normalized coordinates */
export interface Keypoint {
  x: number;
  y: number;
  z: number;
}

/** Single frame of motion data */
export interface MotionFrame {
  /** Timestamp in seconds from capture start */
  t: number;
  /** 33 MediaPipe pose keypoints */
  keypoints: Keypoint[];
}

/** Motion sequence captured from camera */
export interface MotionSequence {
  /** Frames per second of capture */
  fps: number;
  /** Ordered array of frames */
  frames: MotionFrame[];
}

/** Device information for enrollment */
export interface DeviceInfo {
  platform: string;
  userAgent: string;
  screenWidth: number;
  screenHeight: number;
}

/** Result of a presence verification */
export interface VerificationResult {
  /** Whether the verification passed */
  valid: boolean;
  /** Presence Entropy Score (0-1), measures biological motion entropy */
  pes: number;
  /** Raw similarity score (0-1) */
  similarity: number;
  /** Verification threshold used */
  threshold: number;
  /** Risk level applied */
  riskLevel: "low" | "medium" | "high";
  /** Rejection reason (if valid=false) */
  rejectionReason?: string;
  /** Factor breakdown for debugging */
  factors?: VerificationFactors;
}

/** Detailed verification factor breakdown */
export interface VerificationFactors {
  kinematicScore: number;
  accelerationScore: number;
  jerkScore: number;
  jerkSpectrumScore: number;
  combinedScore: number;
}

/** Enrollment data — store this server-side */
export interface Enrollment {
  /** Unique enrollment ID */
  id: string;
  /** User identifier */
  userId: string;
  /** Device used for enrollment */
  device: DeviceInfo;
  /** Encoded motion signature (opaque — do not modify) */
  signatureBlob: string;
  /** When the enrollment was created */
  createdAt: string;
  /** Number of samples used to create this enrollment */
  sampleCount: number;
}

/** Challenge issued by the protocol */
export interface Challenge {
  /** Session key (hex-encoded) */
  sessionKey: string;
  /** Challenge data as JSON string */
  data: string;
  /** When the challenge expires */
  expiresAt: string;
}

/** Server-side validation request */
export interface ValidateRequest {
  /** Enrollment ID to verify against */
  enrollmentId: string;
  /** Proof generated by verifyPresence() */
  proof: string;
  /** Challenge used during verification */
  challenge: string;
}

/** Server-side validation response */
export interface ValidateResponse {
  valid: boolean;
  pes: number;
  similarity: number;
  threshold: number;
}
