"use client";

import { useState, useEffect } from "react";
import ProtocolHeader from "@/components/header/header";
import ProtocolFooter from "@/components/footer/footer";
import { playTick } from "@/utils/useAudioTick";

const SECTIONS = [
  {
    id: "proposition", num: "0", heading: "The Proposition",
    content: `AI can generate a visage. AI can clone a voice. AI can forge a digital identity.
But AI cannot generate you — because you are not a file. You are a field.

This document explains why the most advanced AI models on Earth — including DeepSeek, GPT-5, and multimodal motion diffusion architectures — structurally fail to replicate the deep kinetic signature of a living human entity. It is not a claim about temporary AI limitations. It is a claim about physics, information theory, and the irreducible entropy of biological control systems.`,
  },
  {
    id: "physics", num: "1", heading: "The Physics of Unforgeability",
    content: `The human motor system is not a transformer. It is a multi-scale, non-linear, noise-driven biological control system built from motor units (asynchronous stochastic recruitment at 5–50 Hz), the stretch reflex arc (~25 ms feedback loop producing 8–12 Hz micro-oscillations), the corticospinal tract (50–80 m/s conduction, creating individual-specific timing signatures), cerebellar feedforward (always slightly wrong, producing 3–5 Hz error-correction micro-motions), and musculoskeletal biomechanics (bone lengths, joint surface geometries, tendon stiffness — physically unique to each entity).

These are not "features" that can be extracted and replicated. They are physical properties of a specific human entity.

AI-generated motion, trained with L2 loss, is mathematically optimized to suppress high-frequency, low-amplitude signals — exactly the signals that make human motion human. The optimal L2 predictor is the conditional mean of the training distribution. It converges to the average motion, not any specific human's motion. The result: AI motion looks correct to the human eye but is kinematically sterile — too smooth, too regular, too average.`,
  },
  {
    id: "info-theory", num: "2", heading: "The Information-Theoretic Limit",
    content: `Even with infinite training data, an AI model faces a fundamental information bottleneck:

Nyquist limit: 2D video at 30 fps cannot resolve dynamics above 15 Hz. The 8–12 Hz physiological tremor band is at the Nyquist boundary — its phase information is fundamentally aliased in any video-based training set.

Depth ambiguity: 2D→3D lifting is ill-posed. True skeletal proportions in 3D are underdetermined from 2D projections alone. A femur that appears 42 cm on screen might be anywhere from 38–46 cm — a ±10% uncertainty propagating through the entire kinematic chain.

Sensor noise floor: Even high-quality 3D pose data carries measurement noise at the millimeter scale — precisely the scale of the micro-kinematic signals that distinguish individuals.

The consequence: no finite training dataset can fully determine a target's Motion Signature. There is an irreducible gap — not because AI is not good enough yet, but because the information is not in the data.`,
  },
  {
    id: "engine", num: "3", heading: "The MyShape Motion Signature Engine",
    content: `The MyShape core engine is written in Rust. It compiles to native binaries (macOS, Linux, Windows) and WebAssembly. It has zero runtime dependencies beyond the Rust standard library and a handful of audited cryptographic and linear algebra crates.

The engine extracts a 128-dimensional Motion Signature vector from raw 3D pose sequences across four independent feature groups:

Φ_K — Kinematics (40 dims): Skeletal ratios between 14 bone segments, 6 joint angle variances, velocity and acceleration statistics for 5 representative keypoints.

Φ_A — Acceleration Profile (25 dims): Per-keypoint statistical distribution including Hurst exponent. Human acceleration: H ≈ 0.6–0.8 (long-range dependence). AI acceleration: H ≈ 0.5 (uncorrelated noise).

Φ_J — Jerk Profile (25 dims): The third temporal derivative of position — rate of change of acceleration. Per-keypoint statistics including median absolute deviation and lag-1 autocorrelation. The most unforgeable single kinematic dimension.

Φ_Jspec — Jerk Spectrum (30 dims): Frequency-domain analysis. Energy in 4 frequency bands, spectral slope (log-log power vs frequency), and spectral entropy. Human jerk exhibits 1/f^α scaling (α ≈ 1.0–1.5). AI jerk exhibits α > 2.0 (over-smoothed) or α ≈ 0 (white noise). Neither is human.`,
  },
  {
    id: "results", num: "4", heading: "Live Verification Results",
    content: `The following results were generated by the MyShape CLI demo tool (myshape-demo) running the Rust core engine:

  Test Case              Presence Score   Verdict
  ─────────────────────────────────────────────────
  Genuine Human          0.9817           PASS ✓
  AI Forgery (GPT-5)     0.5857           FAIL ✗
  Impostor               0.0000           FAIL ✗

  Human—AI Gap: 0.3960

The AI forgery failed across four independent rejection dimensions:
  • TREMOR_ABSENT — 8–12 Hz physiological tremor missing
  • JERK_SPECTRUM_ANOMALY — 1/f spectral scaling violated
  • HURST_ANOMALY — Long-range dependence absent
  • OVER_SMOOTHED — Motor micro-perturbations missing`,
  },
  {
    id: "integration", num: "5", heading: "Integration: Five Lines to Proof of Intent",
    content: `TypeScript SDK (Node.js / Deno / Browser via WASM):

  import { MyShapeSDK } from "myshape-sdk";
  const myshape = await MyShapeSDK.init();
  const enrollment = myshape.createEnrollment(signatures, userId, device);
  const challenge = myshape.generateChallenge();
  const result = myshape.verifyIntent(challenge, motion, context, enrollment);
  if (result.verified) { executeTransaction(); }

Native CLI:

  cargo run --release --bin myshape-verify -- \
    --enrollment alice.enroll.json \
    --challenge session.challenge.json \
    --motion captured.motion.json \
    --risk high

Smart Contract (Solidity):

  function transferWithPresence(address to, uint256 amount,
      bytes calldata receipt, bytes calldata sig) external {
    require(verifyNodeSignature(receipt, sig));
    PresenceReceipt memory r = decodeReceipt(receipt);
    require(r.presenceScore >= minScore(amount));
    _transfer(msg.sender, to, amount);
  }`,
  },
  {
    id: "deeper-truth", num: "6", heading: "The Deeper Truth",
    content: `Every AI motion model is a function approximator. It learns a mapping from inputs to outputs. It does not have a spinal cord, motor spindles, a cerebellum, motor neurons firing asynchronously, a stretch reflex arc operating at 25 ms latency, tendons with viscoelastic properties, or joints with anisotropic friction.

An AI can approximate the output of these systems to arbitrary precision given enough data and compute. But the approximation will always be a projection — a lower-dimensional shadow of a higher-dimensional physical process.

The MyShape engine detects the shadow by measuring what the shadow cannot cast: the irreducible entropy of a living entity.

The AI Paradox: The better AI gets at generating realistic motion, the more aggressively it smooths, averages, and regularizes — and the more detectable it becomes to spectral analysis. Every improvement in visual fidelity comes at the cost of spectral fidelity. The AI faces an impossible tradeoff: look more real, or be more real. It cannot do both.`,
  },
  {
    id: "genesis-protocol", num: "7", heading: "Genesis Protocol — The Entropy Source of Trust",
    content: `§7.1 The Logical Primitive

A protocol without an origin is a protocol without sovereignty. Every decentralized system must answer a single question: where does the first bit of trust come from?

In proof-of-work, trust emerges from burned energy. In proof-of-stake, trust emerges from locked capital. In MyShape, trust emerges from the irreducible entropy of a living human entity — measured, verified, and permanently inscribed into the protocol's root index.

A Genesis Node is not a user account. It is an entropy source. It injects the first measurable, unforgeable signal of biological presence into an otherwise deterministic computational system. This signal — the Motion Signature of a specific human entity, verified at initialization — becomes the cryptographic seed from which all subsequent trust derivations flow.

§7.2 The Root Index

When a node completes the Genesis Ritual and achieves GENESIS_NODE status, three things occur at the protocol layer:

1. Identity Commitment. The node's initial Motion Signature hash is written to the protocol_nodes table with status = GENESIS_NODE. This record is immutable — it cannot be downgraded, archived, or revoked. It is a permanent entry in the protocol's identity namespace.

2. Root Entropy Injection. The entropy extracted during the Genesis scan — the full 128-dimensional Motion Signature vector with its associated PES score — becomes part of the protocol's accumulated entropy pool. This pool is the foundation for all future zero-knowledge proof generation.

3. Governance Weight Initialization. The node receives scan_count = 0 and data_contribution = 0 — but its status field carries the genesis flag permanently. Future governance mechanisms (voting weight, proposal submission rights, feature access gating) read this flag at the protocol level, not the application level. The flag is not cosmetic. It is structural.

§7.3 Evolution: From Founding Entity to Validator

The Genesis designation is permanent, but node capability evolves. The protocol defines a growth trajectory measured by two objective metrics:

scan_count — The cumulative number of successful Motion-Signature verifications performed by this node. Each verification requires a live human presence, a camera, and a successful PES threshold crossing. This is not a vanity metric. It measures the node's active contribution to the protocol's entropy pool.

data_contribution — The aggregate entropy value contributed across all scans. Higher scan_count with consistent high-PES scores produces higher data_contribution. This metric distinguishes between a node that verified once and a node that continuously reinforces the protocol's trust substrate.

The progression:

  Founding Entity → scan_count ≥ 50   → Active Validator
  Active Validator → scan_count ≥ 500 → Core Validator
  Core Validator   → data_contribution ≥ 10,000 → Anchor Node

Anchor Nodes form the protocol's long-term trust backbone. Their accumulated entropy contributions are weighted more heavily in multi-party verification scenarios and consensus mechanisms. The path is open to all Genesis Nodes, but it is earned, not granted.

§7.4 Permanent Access as Protocol Metadata

The early_access flag returned by the Node Privileges API is not a feature flag managed by a product team. It is a protocol-level property derived from the genesis flag in the protocol_nodes table. Any future protocol upgrade, governance mechanism, or feature deployment that reads this flag must honor it — not because a policy document says so, but because the protocol's root index says so.

This is the architectural distinction between a "badge" and a "right." A badge is application-layer decoration. A right is protocol-layer metadata that constrains downstream logic. Genesis Nodes bear the latter.

§7.5 The Invitation Mechanism

Genesis Nodes are limited to the first 100 human entities to complete the Genesis Ritual. This is not artificial scarcity. It is bootstrap security. The protocol requires a minimum entropy threshold to initialize its zero-knowledge proof system with statistical significance. One hundred high-entropy human sources, each contributing a 128-dimensional Motion Signature, provide sufficient diversity to establish the initial trust anchor.

New nodes may join the protocol after the Genesis Cohort is sealed, but they enter as ACTIVE nodes — verified, sovereign, and fully functional, but without the permanent genesis flag. The protocol is open. The Genesis is finite.`,
  },
  {
    id: "continuity", num: "8", heading: "The Continuity Horizon",
    content: `Every identity system in production today answers the wrong question.

They ask: Who are you?
They ask: Are you human?

No one asks: Have you been continuously present?

Imagine the digital world of 2030. A single human subject operates through a constellation of agents: a personal agent managing schedules, a work agent executing contracts, a finance agent moving assets, a creative agent producing work, a healthcare agent monitoring vitals. Some of these agents act autonomously for hours or days between human check-ins.

The critical question is not whether these agents are human. The critical question is whether each agent still represents the same human subject — continuously, verifiably, without assumption.

Today, there is no protocol that answers this question.

Accounts can be copied. Profiles can be fabricated. Static identity proofs can be replayed. Continuity cannot be assumed. It must be verified.

This is the long arc of MyShape Protocol.

Phase 1 — Proof of Presence. The 128-dimensional Motion Signature verifies that a living entity is physically present, right now, in front of the sensor. This phase is operational today.

Phase 2 — Proof of Agency. An autonomous agent — carrying delegated authority from its human subject — proves that its authorization chain is unbroken. The agent holds a tamper-proof signature pen, continuously endorsed by verified presence.

Phase 3 — Proof of Continuity. Across devices, across agents, across time — the protocol verifies that the same sovereign subject has been continuously, verifiably present. The continuity proof becomes a new cryptographic primitive: a chain of presence receipts that no adversary can forge.

Phase 4 — Persistent Digital Subjects. The protocol becomes invisible infrastructure. Presence verification dissolves into the network layer. A digital subject is no longer a collection of accounts and credentials — it is a persistent, verifiable entity whose continuity is mathematically guaranteed.

Identity is static. Presence is dynamic. Continuity is the long-term value.

MyShape verifies continuity through presence.

This is not a product roadmap. It is the definition of a new protocol layer — one that the simulation age will require. We invite the world to build it with us.`,
  },
];

export default function WhitepaperClient() {
  const [activeId, setActiveId] = useState("proposition");
  const [tocShow, setTocShow] = useState(true);
  const [genesisNodes, setGenesisNodes] = useState<{ total: number; remaining: number; nodes: Array<{ index: number; id: string; joined: string }> } | null>(null);
  const [prevTotal, setPrevTotal] = useState(0);
  const [nodePulse, setNodePulse] = useState(false);
  const [isSealed, setIsSealed] = useState(false);
  const [glitchActive, setGlitchActive] = useState(false);

  // 实时轮询 Genesis 节点数
  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    const poll = () => {
      fetch("/api/nodes/genesis")
        .then(r => r.json())
        .then(data => {
          if (data.nodes) {
            const wasNotSealed = genesisNodes && genesisNodes.total < 100;
            const nowSealed = data.total >= 100;
            setGenesisNodes(prev => {
              if (prev && data.total > prev.total) {
                setNodePulse(true);
                setTimeout(() => setNodePulse(false), 1200);
              }
              return data;
            });
            if (data.total > prevTotal) setPrevTotal(data.total);
            // 检测封存事件
            if (wasNotSealed && nowSealed) {
              setIsSealed(true);
              setGlitchActive(true);
              setTimeout(() => setGlitchActive(false), 2500);
            }
            if (data.total >= 100) {
              setIsSealed(true);
              clearInterval(interval); // 封存后停止轮询
            }
          }
        })
        .catch(() => {});
    };
    poll();
    interval = setInterval(poll, 15000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) setActiveId(entry.target.id);
        }
      },
      { rootMargin: "-20% 0px -60% 0px" }
    );
    SECTIONS.forEach((s) => {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const check = () => {
      const footer = document.querySelector("footer");
      if (footer) setTocShow(footer.getBoundingClientRect().top > window.innerHeight * 0.5);
    };
    window.addEventListener("scroll", check, { passive: true });
    return () => window.removeEventListener("scroll", check);
  }, []);

  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div className="min-h-screen bg-[#02040a] text-[#f8feff] font-mono selection:bg-[#90c8ff]/30">
      <ProtocolHeader />

      {/* Glitch 封存特效 */}
      {glitchActive && (
        <div className="fixed inset-0 z-50 pointer-events-none" style={{ animation: "glitchShift 0.15s steps(1) infinite" }}>
          <div className="absolute inset-0 border-[3px] border-[#90c8ff]/30" style={{ animation: "glitchBorder 2.5s ease-out forwards", boxShadow: "inset 0 0 120px rgba(144,200,255,0.15), 0 0 80px rgba(144,200,255,0.1)" }} />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#90c8ff]/[0.04] to-transparent" />
        </div>
      )}
      <div className="relative z-10 max-w-6xl mx-auto px-4 md:px-6 pt-24 md:pt-28 pb-16 flex flex-col md:flex-row gap-12 md:gap-24">
        {/* Spacer */}
        <div className="md:w-56 shrink-0 hidden md:block" />
        {/* ── Sidebar Nav ── */}
        <aside className="hidden md:block" style={{
          position: "fixed", top: "128px", width: "224px",
          left: "max(24px, calc((100vw - 1152px) / 2 + 24px))",
          opacity: tocShow ? 1 : 0, pointerEvents: tocShow ? "auto" : "none",
          transition: "opacity 0.3s", zIndex: 10,
        }}>
          <div className="text-[#90c8ff]/40 text-[10px] tracking-[0.5em] uppercase mb-10 font-mono font-bold">
            // ON_THIS_PAGE
          </div>
          <ul className="space-y-8 border-l" style={{ borderColor: "rgba(144,200,255,0.08)" }}>
            {SECTIONS.map((s) => {
              const isActive = s.id === activeId;
              return (
                <li key={s.id}>
                  <button
                    onClick={() => scrollTo(s.id)}
                    onMouseEnter={() => playTick(600, "sine", 0.06, 0.015)}
                    className="block text-left w-full transition-all duration-300"
                    style={{
                      borderLeft: isActive ? "2px solid rgba(144,200,255,0.8)" : "2px solid transparent",
                      marginLeft: "-1px",
                      paddingLeft: "20px",
                      background: isActive ? "linear-gradient(90deg, rgba(144,200,255,0.06), transparent)" : "transparent",
                    }}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`w-1 h-1 rounded-full shrink-0 transition-all duration-300 ${isActive ? "bg-[#90c8ff] shadow-[0_0_6px_rgba(144,200,255,0.6)] scale-100" : "bg-transparent scale-0"}`} />
                      <span className="text-[10px] tracking-[0.3em] transition-all duration-300"
                        style={{
                          color: isActive ? "rgba(144,200,255,0.8)" : "rgba(255,255,255,0.1)",
                          textShadow: isActive ? "0 0 10px rgba(144,200,255,0.3)" : "none",
                        }}>
                        {s.num}
                      </span>
                    </div>
                    <div className="text-[12px] tracking-[0.2em] uppercase transition-all duration-300"
                      style={{
                        color: isActive ? "rgba(144,200,255,0.95)" : "rgba(255,255,255,0.2)",
                        textShadow: isActive ? "0 0 12px rgba(144,200,255,0.4)" : "none",
                      }}>
                      {s.heading}
                    </div>
                  </button>
                </li>
              );
            })}
          </ul>
        </aside>

        {/* ── Main Content ── */}
        <div className="flex-1 min-w-0">
          {/* Header */}
          <div className="mb-28">
            <div className="text-[#90c8ff]/50 text-[10px] tracking-[0.5em] uppercase mb-6">
              TECHNICAL_WHITEPAPER // V2.0_CONTINUITY
            </div>
            <h1 className="text-3xl md:text-4xl font-bold tracking-tighter text-white leading-tight mb-6">
              Why DeepSeek and GPT-5<br />
              <span className="text-[#90c8ff]/80">Cannot Forge</span> the Human Kinetic Signature
            </h1>
            <div className="flex items-center gap-3 text-[12px]">
              <span className="text-white/30">MyShape Protocol</span>
              <span className="text-white/10">·</span>
              <span className="text-white/30">June 2026</span>
              <span className="text-white/10">·</span>
              <span className="text-white/30">v0.1</span>
            </div>
            <div className="flex items-center gap-3 mt-4">
              <span className="flex items-center gap-1.5 text-[#90c8ff]/60 text-[10px] tracking-[0.2em] uppercase">
                <span className="w-1.5 h-1.5 rounded-full bg-[#90c8ff] shadow-[0_0_6px_rgba(144,200,255,0.6)] animate-pulse" />
                Engine v0.1.0
              </span>
              <span className="text-white/10">|</span>
              <span className="text-white/25 text-[10px]">25/25 tests pass</span>
              <span className="text-white/10">|</span>
              <span className="text-white/25 text-[10px]">Human—AI Gap: 0.3960</span>
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-52">
            {SECTIONS.map((section) => (
              <section key={section.id} id={section.id} className="scroll-mt-40 pt-16 first:pt-0 group"
                onMouseEnter={() => playTick(600, "sine", 0.04, 0.022)}>
                <h2 className="text-2xl md:text-3xl font-bold tracking-tighter text-white mb-8 uppercase transition-colors duration-500 group-hover:text-[#90c8ff]/80">
                  <span className="text-[#90c8ff]/60 mr-3">{section.num}.</span>
                  {section.heading}
                </h2>
                <div className="space-y-6 text-white/50 text-[18px] leading-[1.85] font-light">
                  {section.content.split("\n\n").map((para, i) => (
                    <p key={i}>{para.trim()}</p>
                  ))}
                </div>

                {section.id === "results" && (
                  <div className="border p-6 my-8" style={{ borderColor: "rgba(144,200,255,0.1)" }}>
                    <pre className="text-white/45 text-[12px] leading-relaxed font-mono whitespace-pre">
                      {`  Test Case              Presence Score   Verdict
  ─────────────────────────────────────────────────
  Genuine Human          0.9817           PASS ✓
  AI Forgery (GPT-5)     0.5857           FAIL ✗
  Impostor               0.0000           FAIL ✗

  Human—AI Gap: 0.3960`}
                    </pre>
                  </div>
                )}

                {section.id === "genesis-protocol" && genesisNodes && (
                  <div className="space-y-6 my-10">
                    {/* Genesis Cohort 实时状态 */}
                    <div className="border p-6" style={{ borderColor: "rgba(144,200,255,0.15)", background: "rgba(4,14,28,0.5)" }}>
                      <div className="flex items-center gap-3 mb-4">
                        <span className={`w-2 h-2 rounded-full ${isSealed ? "bg-[#90c8ff] shadow-[0_0_12px_rgba(144,200,255,0.9)]" : "bg-[#90c8ff] shadow-[0_0_8px_rgba(144,200,255,0.8)] animate-pulse"}`} />
                        <span className="text-[#90c8ff]/60 text-[10px] tracking-[0.4em] uppercase">
                          {isSealed ? "Genesis Cohort — Sealed & Immutable" : "Genesis Cohort — Live Registry"}
                        </span>
                        {isSealed && (
                          <span className="text-[#90c8ff]/40 text-[10px] tracking-[0.2em] border border-[#90c8ff]/20 px-2 py-0.5">FINAL</span>
                        )}
                      </div>

                      <div className="flex items-baseline gap-4 mb-4">
                        <span className="text-5xl font-light font-mono text-[#90c8ff]/80">{genesisNodes.total}</span>
                        <span className="text-white/30 text-[12px] tracking-[0.2em] uppercase">of 100 slots claimed</span>
                        <span className="text-[#90c8ff]/40 text-[10px]">— {genesisNodes.remaining} remaining</span>
                      </div>

                      {/* 协议同步进度条 */}
                      <div className="mb-6">
                        {isSealed ? (
                          <div className="text-center py-3 border border-[#90c8ff]/20 bg-[#90c8ff]/[0.03]">
                            <div className="text-[#90c8ff]/80 text-[10px] tracking-[0.4em] uppercase font-mono mb-1">◈ COHORT_SEALED ◈</div>
                            <div className="text-white/25 text-[10px] tracking-[0.2em] uppercase">Identity Layer Anchored — Registry Immutable</div>
                          </div>
                        ) : (
                          <>
                            <div className="flex items-center justify-between mb-1.5">
                              <span className="text-white/30 text-[10px] tracking-[0.3em] uppercase">Protocol Sync</span>
                              <span className="text-[#90c8ff]/30 font-mono text-[10px]">{(genesisNodes.total / 100 * 100).toFixed(1)}%</span>
                            </div>
                            <div className="relative h-1 bg-white/[0.04] overflow-hidden">
                              <div
                                className={`absolute inset-y-0 left-0 bg-gradient-to-r from-[#90c8ff]/40 via-[#90c8ff]/60 to-[#90c8ff]/40 transition-all duration-1000 ease-out ${nodePulse ? "animate-pulse" : ""}`}
                                style={{
                                  width: `${Math.max(genesisNodes.total / 100 * 100, 1)}%`,
                                  boxShadow: nodePulse ? "0 0 12px rgba(144,200,255,0.6)" : "0 0 4px rgba(144,200,255,0.2)",
                                }}
                              />
                              <div className="absolute inset-y-0 w-full pointer-events-none" style={{ background: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.03) 50%, transparent 100%)", backgroundSize: "200% 100%", animation: "shimmer 3s ease-in-out infinite" }} />
                            </div>
                            <div className="flex items-center gap-1.5 mt-1">
                              <span className={`w-1 h-1 rounded-full transition-all duration-500 ${nodePulse ? "bg-[#90c8ff] shadow-[0_0_6px_rgba(144,200,255,0.8)]" : "bg-[#90c8ff]/30"}`} />
                              <span className="text-white/30 text-[10px] tracking-[0.2em] uppercase">
                                {genesisNodes.total === 0 ? "Awaiting genesis initialization" :
                                 genesisNodes.total < 100 ? "Network bootstrapping in progress" :
                                 "Genesis Cohort sealed — network active"}
                              </span>
                            </div>
                          </>
                        )}
                      </div>

                      {genesisNodes.nodes.length > 0 && (
                        <div className={`grid ${isSealed ? "grid-cols-3 md:grid-cols-5" : "grid-cols-2 md:grid-cols-4"} gap-2`}>
                          {genesisNodes.nodes.slice(0, isSealed ? 100 : 20).map(n => (
                            <div key={n.index} className="flex items-center gap-2 p-2 border text-[10px] font-mono transition-all duration-500"
                              style={{
                                borderColor: isSealed ? "rgba(144,200,255,0.1)" : "rgba(255,255,255,0.04)",
                                background: isSealed ? "rgba(4,14,28,0.8)" : "rgba(2,4,10,0.6)",
                              }}>
                              <span className="text-white/30 text-[10px] w-5">#{n.index}</span>
                              <span className="text-white/25 truncate">{n.id}</span>
                            </div>
                          ))}
                          {!isSealed && genesisNodes.total > 20 && (
                            <div className="flex items-center justify-center p-2 border border-white/[0.02] text-[10px] text-white/30 font-mono">
                              +{genesisNodes.total - 20} more
                            </div>
                          )}
                        </div>
                      )}
                      {isSealed && (
                        <div className="text-center mt-4 pt-3 border-t border-[#90c8ff]/10">
                          <span className="text-[#90c8ff]/30 text-[10px] tracking-[0.3em] uppercase font-mono">
                            ◈ Genesis Registry — Permanently Anchored to Protocol Root Index
                          </span>
                        </div>
                      )}
                    </div>

                    {/* CTA */}
                    <div className="text-center pt-4">
                      <a href="/genesis"
                        onMouseEnter={() => playTick(800, "sine", 0.10, 0.025)}
                        className="inline-flex items-center gap-2 px-8 py-3 border text-[#90c8ff]/70 text-[10px] tracking-[0.3em] uppercase font-mono hover:bg-[#90c8ff]/[0.04] transition-all"
                        style={{ borderColor: "rgba(144,200,255,0.3)" }}>
                        Initialize Genesis <span className="text-[#90c8ff]/50">→</span>
                      </a>
                    </div>
                  </div>
                )}

                {section.id === "integration" && (
                  <div className="space-y-3 my-8">
                    <div className="border p-5" style={{ borderColor: "rgba(144,200,255,0.1)" }}>
                      <div className="text-[#90c8ff]/40 text-[10px] tracking-[0.3em] uppercase mb-3 font-mono">TypeScript SDK</div>
                      <pre className="text-[#90c8ff]/60 text-[12px] leading-relaxed font-mono whitespace-pre-wrap">
{`import { MyShapeSDK } from "myshape-sdk";

const myshape = await MyShapeSDK.init();
const enrollment = myshape.createEnrollment(sigs, userId, device);
const challenge = myshape.generateChallenge();
const result = myshape.verifyIntent(
  challenge, motion, context, enrollment
);
if (result.verified) { executeTransaction(); }`}
                      </pre>
                    </div>
                    <div className="border p-5" style={{ borderColor: "rgba(144,200,255,0.1)", background: "rgba(2,4,10,0.6)" }}>
                      <div className="text-white/30 text-[10px] tracking-[0.3em] uppercase mb-3 font-mono">Native CLI</div>
                      <pre className="text-[#90c8ff]/35 text-[12px] leading-relaxed font-mono whitespace-pre-wrap">
{`cargo run --release --bin myshape-verify -- \\
  --enrollment alice.enroll.json \\
  --challenge session.challenge.json \\
  --motion captured.motion.json \\
  --risk high`}
                      </pre>
                    </div>
                  </div>
                )}
              </section>
            ))}
          </div>

          {/* Footer CTA */}
          <div className="mt-28 pt-12 border-t" style={{ borderColor: "rgba(144,200,255,0.08)" }}>
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div className="space-y-1">
                <p className="text-white/30 text-[10px] tracking-[0.3em] uppercase font-mono">Ready to integrate?</p>
                <p className="text-white/30 text-[12px]">Five lines of code. Zero data stored. Real human presence.</p>
              </div>
              <a href="/developers"
                className="inline-flex items-center gap-2 px-5 py-2.5 border text-[#90c8ff]/70 text-[10px] tracking-[0.2em] uppercase font-mono hover:bg-[#90c8ff]/[0.04] transition-all"
                style={{ borderColor: "rgba(144,200,255,0.25)" }}
                onMouseEnter={() => playTick(700, "sine", 0.08, 0.02)}>
                View SDK Reference <span className="text-[#90c8ff]/40">→</span>
              </a>
            </div>
          </div>
        </div>
      </div>

      <ProtocolFooter />
    </div>
  );
}
