"use client";
import ProtocolHeader from "@/components/header/header";
import ProtocolFooter from "@/components/footer/footer";
import BackgroundParticles from "@/components/particles/BackgroundParticles";
import Link from "next/link";
import { playTick } from "@/utils/useAudioTick";

const SECTIONS = [
  { id: "hierarchy", heading: "The Identity Signal Hierarchy",
    content: `Every identity verification system relies on a signal — something the prover presents to convince the verifier of their identity. Not all signals are equal.\n\nKnowledge factors (passwords, PINs, secret questions): can be stolen, guessed, or phished. Transferable. Replayable. The weakest signal.\n\nPossession factors (hardware tokens, phone SMS, authenticator apps): can be lost, stolen, or SIM-swapped. Transferable but harder to duplicate. Medium signal.\n\nStatic biometrics (fingerprints, face scans, iris patterns): cannot be forgotten or lost — but can be captured, replayed, and deepfaked. Once compromised, permanently broken. Non-transferable in theory but replayable in practice.\n\nBehavioral signals (typing rhythm, gait, voice pattern): harder to steal than biometrics but can be observed, recorded, and mimicked by AI. Semi-transferable.\n\nMotion-signature: a real-time performance of biological movement. Each verification is fresh. Each signature is temporally unique. The entropy characteristics of human motion — micro-timing variance at the millisecond level, physiological tremor at 8-12 Hz, motor unit recruitment stochasticity — are mathematically impossible for any known AI architecture to reproduce. Non-transferable. Non-replayable. The strongest signal.` },
  { id: "three-limits", heading: "The Three Hard Limits That Make Motion Unforgeable",
    content: `AI cannot forge human motion at the resolution required to defeat motion-signature verification. This is not a claim about the current state of AI. It is a mathematical consequence of three hard limits.\n\n1. The Nyquist Limit\nStandard cameras capture at 30 frames per second. The Nyquist-Shannon sampling theorem states that a signal sampled at 30 Hz cannot resolve frequency components above 15 Hz. Human motion contains information above 15 Hz — physiological tremor (8-12 Hz), ballistic movement corrections (20-50 Hz), and motor unit firing patterns (up to 100 Hz). An AI model trained on 30 fps data literally cannot see the full temporal resolution of human motion. Its output will always lack the high-frequency entropy that characterizes biological movement.\n\n2. Depth Ambiguity\nA 2D camera observing a 3D human introduces irreducible depth ambiguity. MediaPipe's 33-landmark model estimates 3D positions from 2D images using a learned prior — but this prior introduces ±10% skeletal proportion uncertainty. Human motion exploits true 3D kinematics: slight rotations, perspective shifts, depth-parallax effects. AI-generated 2D video, when projected to 3D, produces kinematics that are detectably different from true 3D human movement because the depth information was never really there.\n\n3. The Entropy Gap\nHuman motion is driven by a biological control system that introduces irreducible noise. Motor unit recruitment is stochastic — the nervous system does not activate the exact same muscle fibers in the exact same sequence each time. Muscle fiber contraction has micro-variance — sarcomere shortening is a molecular process with thermal noise. Neural signal propagation has timing jitter — synaptic delays vary at the sub-millisecond level. AI-generated motion is the output of a deterministic function — even with stochastic sampling, the entropy characteristics (Hurst exponent, approximate entropy, detrended fluctuation analysis) are provably different from biological motion. The PES engine quantifies this gap. Human motion: 70-95. AI: <20. The gap is mathematical.` },
  { id: "why-now", heading: "Why This Matters Right Now",
    content: `We are entering an era where the ability to distinguish human from AI is not a philosophical question — it is an economic necessity.\n\nA DeFi protocol processing $1B in daily volume needs to know: is the entity executing this trade a human with continuous sovereign control, or an AI agent that may have been compromised?\n\nA DAO voting on a $50M treasury allocation needs to know: are these votes coming from unique humans, or from a Sybil attack using AI-generated identities?\n\nA credential issuer needs to know: is the entity presenting this Verifiable Credential the same continuous subject that received it six months ago, or has the credential been transferred?\n\nMotion-signature verification answers these questions. Not with a heuristic. Not with a "probably." With a mathematical proof rooted in the physics of biological control systems and verified through zero-knowledge cryptography.\n\nThe strongest identity signal is not the one that is hardest to steal. It is the one that is impossible to forge. Motion is that signal.` },
];

export default function PostClient() {
  return (
    <div className="bg-[#02040a] text-[#f8feff] font-mono selection:bg-[#90c8ff]/30 min-h-screen flex flex-col">
      <ProtocolHeader />
      <main className="flex-1 relative"><BackgroundParticles />
        <div className="relative z-10 max-w-3xl mx-auto px-4 md:px-6" style={{ paddingTop: "8rem", paddingBottom: "6rem" }}>
          <div className="space-y-4 mb-16"><div className="flex items-center gap-4 text-[#90c8ff]/40 text-[9px] tracking-[0.3em] uppercase"><span>GENESIS 013</span><span className="w-8 h-[1px] bg-[#90c8ff]/20" /><span>2026.07.03</span></div><h1 className="text-2xl md:text-3xl font-light tracking-[0.08em] text-white leading-tight">Why Motion Is<br /><span className="text-[#90c8ff]">Unforgeable</span></h1><p className="text-white/30 text-[11px] tracking-[0.1em] leading-relaxed max-w-xl">The physics of irreducible entropy. Why the way you move is the only identity signal that AI cannot forge — mathematically.</p></div>
          <div className="space-y-20">{SECTIONS.map(s => (<section key={s.id} id={s.id}><h2 className="text-white/60 text-[11px] tracking-[0.25em] uppercase mb-6 flex items-center gap-3"><span className="w-6 h-[1px] bg-[#90c8ff]/30" />{s.heading}</h2><div className="text-white/50 text-[12px] leading-relaxed tracking-[0.06em] space-y-5 whitespace-pre-line">{s.content}</div></section>))}</div>
          <div className="my-16 h-px bg-gradient-to-r from-transparent via-[#90c8ff]/15 to-transparent" />
          <div className="space-y-4"><p className="text-white/30 text-[9px] tracking-[0.25em] uppercase text-center">Continue Reading</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <Link href="/blog/motion-vs-biometrics-why-your-face-is-not-a-password" onMouseEnter={() => playTick(700,"sine",0.08,0.02)} className="block p-4 border border-[#90c8ff]/10 hover:border-[#90c8ff]/25 transition-all"><p className="text-white/50 text-[10px] tracking-[0.1em]">Motion vs Biometrics</p><p className="text-white/20 text-[8px] tracking-[0.1em] mt-1">Why your face is not a password →</p></Link>
            <Link href="/blog/zero-knowledge-proofs-digital-identity-explained" onMouseEnter={() => playTick(700,"sine",0.08,0.02)} className="block p-4 border border-[#90c8ff]/10 hover:border-[#90c8ff]/25 transition-all"><p className="text-white/50 text-[10px] tracking-[0.1em]">Zero-Knowledge Proofs Explained</p><p className="text-white/20 text-[8px] tracking-[0.1em] mt-1">ZK for digital identity →</p></Link>
            <Link href="/whitepaper" onMouseEnter={() => playTick(700,"sine",0.08,0.02)} className="block p-4 border border-[#90c8ff]/10 hover:border-[#90c8ff]/25 transition-all"><p className="text-white/50 text-[10px] tracking-[0.1em]">MyShape Whitepaper</p><p className="text-white/20 text-[8px] tracking-[0.1em] mt-1">Why AI cannot forge kinetics →</p></Link>
          </div></div>
          <div className="mt-12 p-8 border border-[#90c8ff]/15 bg-[#90c8ff]/[0.02] text-center space-y-4"><p className="text-white/40 text-[10px] tracking-[0.15em] uppercase">See the Physics in Action</p><div className="flex justify-center gap-4 pt-2"><Link href="/motion-demo" onMouseEnter={() => playTick(700,"sine",0.08,0.02)} className="px-6 py-2 border border-[#90c8ff]/30 text-[#90c8ff]/60 text-[9px] tracking-[0.2em] uppercase hover:bg-[#90c8ff]/10 hover:text-[#90c8ff] transition-all">Motion Demo →</Link><Link href="/genesis" onMouseEnter={() => playTick(700,"sine",0.08,0.02)} className="px-6 py-2 border border-[#90c8ff]/15 text-[#90c8ff]/40 text-[9px] tracking-[0.2em] uppercase hover:border-[#90c8ff]/30 hover:text-[#90c8ff]/60 transition-all">Genesis →</Link></div></div>
          <div className="mt-12 text-center"><Link href="/blog" className="text-white/15 text-[9px] tracking-[0.2em] uppercase hover:text-white/40 transition-colors">← Protocol Log</Link></div>
        </div>
      </main>
      <ProtocolFooter />
    </div>
  );
}
