/** @experimental ZK subsystem — under active research. Not production-grade. */
// ============================================================
// MyShape Protocol — Proof System v1.0
// Derived from: Technical Specification v1.0 §6
//
// Three-layer architecture:
//   Layer 1 — Local Proof Generation (PoP, MP, EP)
//   Layer 2 — Zero-Knowledge Layer (ZK-Presence)
//   Layer 3 — Verification Layer (external verifier nodes)
// ============================================================

import type { MotionVectorFinal } from "@/types/motion-vector";
import type { PESComponents } from "./presence-entropy";
import { generateZKPresenceProof as generateCircuitProof } from "./zk-circuit";
import { sha256 as nobleSha256 } from "@noble/hashes/sha2.js";
import { bytesToHex } from "@noble/hashes/utils.js";

// ── §6.2 — Presence Proof (PoP) ──
// H(FV) — hash of the Feature Vector. The smallest verifiable unit.

export interface PresenceProof {
  version: 1;
  proof_type: "PoP";
  pop_hash: string;           // H(FV) using ZK-friendly hash
  mv_hash: string;            // reference to source Motion Vector
  timestamp: number;
  window_seconds: number;
}

// ── §6.3 — Motion Proof (MP) ──
// Proves: MV was generated by real hardware within the time window.

export interface MotionProof {
  version: 1;
  proof_type: "MP";
  mp_hash: string;            // H(MV_meta)
  fps: number;
  window_seconds: number;
  nodes: number;
  timestamp: number;
  device_salt?: string;
}

// ── §6.4 — Entropy Proof (EP) ──
// Proves: MV exceeds entropy floor and is below AI ceiling.

export interface EntropyProof {
  version: 1;
  proof_type: "EP";
  ep_hash: string;            // H(PES, H_f, σ_timing, ε)
  pes: number;
  frequency_entropy: number;
  micro_timing_variance: number;
  noise_residual: number;
  biological_perturbation: number;
  timestamp: number;
}

// ── §6.5 — Zero-Knowledge Presence (ZKP) ──
// Composite proof: ZKP = ZK(PoP, MP, EP)
// Reveals: nothing about raw motion, behavior, identity, or device.

export interface ZKPresenceProof {
  version: 1;
  proof_type: "ZK-Presence";
  zkp_hash: string;           // root hash of all three sub-proofs
  zk_commitment?: string;     // Pedersen commitment (real ZK proof)
  pop: PresenceProof;
  mp: MotionProof;
  ep: EntropyProof;
  generated_at: number;
  expires_at: number;         // timestamp + window
  device_salt?: string;
}

// ── §6.9.3 — Verification result ──

export interface VerificationResult {
  valid: boolean;
  checks: {
    zkp_valid: boolean;
    entropy_threshold: boolean;   // PES ≥ PES_min
    timestamp_valid: boolean;     // within window
    non_replay: boolean;          // PoP not previously seen
    device_integrity: boolean;    // device not revoked
  };
  verified_at: number;
  verifier_node?: string;
}

// ── Hash utilities ──
function sha256(data: string): string {
  return bytesToHex(nobleSha256(new TextEncoder().encode(data)));
}

// ── §6.2 — Generate Presence Proof ──

export function generatePresenceProof(
  mv: MotionVectorFinal,
  featureHash: string,
): PresenceProof {
  const proofData = `${mv.mv_hash}:${featureHash}:${mv.timestamp}:${mv.window}`;
  return {
    version: 1,
    proof_type: "PoP",
    pop_hash: sha256(proofData),
    mv_hash: mv.mv_hash,
    timestamp: mv.timestamp,
    window_seconds: mv.window,
  };
}

// ── §6.3 — Generate Motion Proof ──

export function generateMotionProof(
  fps: number,
  windowSeconds: number,
  nodes: number,
  timestamp: number,
  deviceSalt?: string,
): MotionProof {
  const saltPart = deviceSalt ?? "unsalted";
  const proofData = `${fps}:${windowSeconds}:${nodes}:${timestamp}:${saltPart}`;
  return {
    version: 1,
    proof_type: "MP",
    mp_hash: sha256(proofData),
    fps,
    window_seconds: windowSeconds,
    nodes,
    timestamp,
    device_salt: deviceSalt,
  };
}

// ── §6.4 — Generate Entropy Proof ──

export function generateEntropyProof(
  pes: number,
  components: PESComponents,
  timestamp: number,
): EntropyProof {
  const proofData = `${pes.toFixed(4)}:${components.frequencyEntropy.toFixed(4)}:${components.microTimingVariance.toFixed(4)}:${components.noiseResidual.toFixed(4)}`;
  return {
    version: 1,
    proof_type: "EP",
    ep_hash: sha256(proofData),
    pes,
    frequency_entropy: components.frequencyEntropy,
    micro_timing_variance: components.microTimingVariance,
    noise_residual: components.noiseResidual,
    biological_perturbation: components.biologicalPerturbation,
    timestamp,
  };
}

// ── §6.5 — Generate ZK-Presence Proof ──

/** @deprecated Use CPS-0001 buildReceipt() instead. */
export function generateZKPresenceProof(
  pop: PresenceProof,
  mp: MotionProof,
  ep: EntropyProof,
  deviceSalt?: string,
): ZKPresenceProof {
  const rootData = `${pop.pop_hash}:${mp.mp_hash}:${ep.ep_hash}`;
  const zkp_hash = sha256(rootData);

  // Generate real ZK commitment via Pedersen + Schnorr circuit
  const zkResult = generateCircuitProof(
    `${pop.pop_hash}:${ep.pes}`,
    deviceSalt ?? "myshape",
  );

  return {
    version: 1,
    proof_type: "ZK-Presence",
    zkp_hash,
    zk_commitment: zkResult.commitment.commitment,
    pop,
    mp,
    ep,
    generated_at: Math.floor(Date.now() / 1000),
    expires_at: Math.floor(Date.now() / 1000) + Math.max(pop.window_seconds, mp.window_seconds),
    device_salt: deviceSalt,
  };
}

// ── §6.8 — Verify ZK-Presence Proof ──

/** @deprecated Use CPS-0001 verifyReceipt() instead. */
export function verifyZKPresenceProof(
  proof: ZKPresenceProof,
  options: { pes_min?: number; max_age_seconds?: number } = {},
): VerificationResult {
  const now = Math.floor(Date.now() / 1000);
  const pesMin = options.pes_min ?? 0.20;
  const maxAge = options.max_age_seconds ?? 300; // default 5 min

  // §6.8.1 ZKP validity — recompute root hash
  const recomputedRoot = sha256(`${proof.pop.pop_hash}:${proof.mp.mp_hash}:${proof.ep.ep_hash}`);

  // §6.8.2 Entropy threshold
  const entropyCheck = proof.ep.pes >= pesMin;

  // §6.8.3 Timestamp validity
  const timestampCheck = now <= proof.expires_at && (now - proof.generated_at) <= maxAge;

  // §6.8.4 Non-replay — stub (requires external replay registry)
  const nonReplay = true;

  // §6.8.5 Device integrity — stub (requires external revocation list)
  const deviceIntegrity = true;

  return {
    valid: recomputedRoot === proof.zkp_hash && entropyCheck && timestampCheck && nonReplay && deviceIntegrity,
    checks: {
      zkp_valid: recomputedRoot === proof.zkp_hash,
      entropy_threshold: entropyCheck,
      timestamp_valid: timestampCheck,
      non_replay: nonReplay,
      device_integrity: deviceIntegrity,
    },
    verified_at: now,
  };
}

// ── Full pipeline: raw data → ZK-Presence Proof ──

export interface ProofGenerationInput {
  fps: number;
  windowSeconds: number;
  nodes: number;
  mvHash: string;
  featureHash: string;
  pes: number;
  pesComponents: PESComponents;
  deviceSalt?: string;
}

/** @deprecated Use CPS-0001 buildReceipt() instead. */
export function generateFullProof(input: ProofGenerationInput): ZKPresenceProof {
  const timestamp = Math.floor(Date.now() / 1000);

  const mv: MotionVectorFinal = {
    version: 1,
    fps: input.fps,
    window: input.windowSeconds,
    nodes: input.nodes,
    mv_hash: input.mvHash,
    entropy_score: input.pes,
    timestamp,
    device_salt: input.deviceSalt,
  };

  const pop = generatePresenceProof(mv, input.featureHash);
  const mp = generateMotionProof(input.fps, input.windowSeconds, input.nodes, timestamp, input.deviceSalt);
  const ep = generateEntropyProof(input.pes, input.pesComponents, timestamp);

  return generateZKPresenceProof(pop, mp, ep, input.deviceSalt);
}
