import type { Metadata } from "next";
import HomeClient from "./HomeClient";
import FaqJsonLd from "@/components/seo/FaqJsonLd";

// Prevent static generation — force dynamic render to avoid Vercel CDN staleness
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "MyShape Protocol — CPS-0001 Motion-Signature Continuity Verification",
  description:
    "CPS-0001 Continuity Protocol v1.0-RC1 — engine-independent continuity verification with cryptographically verifiable receipts. verifyContinuity() → PASS / FAIL / INSUFFICIENT_EVIDENCE. Run a verification at /try. Open protocol, research-driven by The Continuity Lab.",
  keywords: [
    "MyShape Protocol",
    "CPS-0001",
    "continuity verification",
    "motion-signature",
    "presence entropy score",
    "two-stage verification",
    "continuity proof",
    "The Continuity Lab",
    "open protocol",
  ],
  alternates: { canonical: "https://www.myshape.com" },
  openGraph: {
    title: "MyShape Protocol — CPS-0001 Motion-Signature Continuity Verification",
    description:
      "CPS-0001 Continuity Protocol v1.0-RC1 — engine-independent continuity verification. Run a verification → motion-signature presence check, no static identity stored.",
    url: "https://www.myshape.com",
    siteName: "MyShape Protocol",
    images: [{ url: "/og-image.png", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "MyShape Protocol — CPS-0001 Motion-Signature Continuity Verification",
    description:
      "CPS-0001 Continuity Protocol v1.0-RC1 — engine-independent continuity verification. Run a verification.",
    images: ["/og-image.png"],
  },
};

export default function HomePage() {
  return (
    <>
      <FaqJsonLd
        mainEntityUrl="https://www.myshape.com"
        questions={[
          {
            question: "What is MyShape Protocol?",
            answer:
              "MyShape Protocol is an open research framework investigating whether digital continuity can become a verifiable property. It analyzes motion patterns through motion-signature technology — an on-device approach that verifies continuous presence without storing personal visual data or any personally identifiable information.",
          },
          {
            question: "How is MyShape different from static identity systems?",
            answer:
              "Static identity systems store fixed attributes that, once compromised, can never be replaced. MyShape verifies dynamic presence — the way an entity moves — rather than static attributes. Motion is generative and inexhaustible: each verification produces a fresh cryptographic proof, and temporal uniqueness raises the cost of replay. No physical identity data is stored or transmitted by default.",
          },
          {
            question: "What is Proof of Continuity?",
            answer:
              "Proof of Continuity is the cryptographic primitive at the heart of MyShape. It records a bounded observation interval — across sessions, devices, and agents — as an independently verifiable signed receipt. Unlike a snapshot credential, a receipt must be regenerated by a live, present entity — raising the cost of replay and copying.",
          },
          {
            question: "Can AI agents use MyShape Protocol?",
            answer:
              "Yes. MyShape is designed for the Agent Economy where human and AI identities coexist. AI agents can participate as entities holding their own keys, without a separate registration protocol. However, maintaining a convincing continuous presence over time requires sustained physical interaction — raising the cost of prolonged impersonation; not established as infeasible.",
          },
        ]}
      />
      {/* Speakable — voice search eligibility for Google Assistant / Alexa */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "@id": "https://www.myshape.com/#webpage",
            url: "https://www.myshape.com",
            speakable: {
              "@type": "SpeakableSpecification",
              cssSelector: ["h1", ".hero-demo-tagline"],
            },
          }),
        }}
      />
      <HomeClient />
    </>
  );
}
