import type { Metadata } from "next";
import HomeClient from "./HomeClient";
import FaqJsonLd from "@/components/seo/FaqJsonLd";

// Prevent static generation — force dynamic render to avoid Vercel CDN staleness
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "MyShape Protocol — The Sovereign 3D Identity Layer for the Decentralized Human",
  description:
    "AI-native identity. Zero-knowledge presence. Motion-signature verification. From signals to trust — explore the Continuity Layer through live PES demo, constellation research, diagnostic console, declassified evidence dossier, and sonar open questions. Built by The Continuity Lab.",
  keywords: [
    "MyShape Protocol",
    "continuity layer",
    "motion-signature verification",
    "AI-native identity",
    "zero-knowledge presence",
    "sovereign identity",
    "presence entropy score",
    "CPS-0001",
    "continuity proof",
    "decentralized identity",
    "proof of continuity",
    "motion biometrics alternative",
    "The Continuity Lab",
  ],
  alternates: { canonical: "https://www.myshape.com" },
  openGraph: {
    title: "MyShape Protocol — Motion-Signature Continuity Verification",
    description:
      "AI can generate faces, voices, identities. But can it maintain continuous presence? MyShape investigates continuity — the one thing AI cannot forge. Live PES engine. Open protocol. Research-driven.",
    url: "https://www.myshape.com",
    siteName: "MyShape Protocol",
    images: [{ url: "/og-image.png", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "MyShape Protocol — Motion-Signature Continuity Verification",
    description:
      "AI can generate everything. But can it maintain continuous presence? MyShape investigates the one thing AI cannot forge.",
    images: ["/og-image.png"],
  },
};

export default function HomePage() {
  return (
    <>
      <FaqJsonLd
        mainEntityUrl="https://www.myshape.com"
        questions={[
          {
            question: "What is MyShape Protocol?",
            answer:
              "MyShape Protocol is an open research framework investigating whether digital continuity can become a verifiable property. It analyzes motion patterns through motion-signature technology — a zero-knowledge approach that verifies continuous presence without storing personal visual data or any personally identifiable information.",
          },
          {
            question: "How is MyShape different from static identity systems?",
            answer:
              "Static identity systems store fixed attributes that, once compromised, can never be replaced. MyShape verifies dynamic presence — the way an entity moves — rather than static attributes. Motion is generative and inexhaustible: each verification is a fresh cryptographic proof that cannot be replayed or stolen. No physical identity data is ever stored or transmitted.",
          },
          {
            question: "What is Proof of Continuity?",
            answer:
              "Proof of Continuity is the cryptographic primitive at the heart of MyShape. It records a bounded observation interval — across sessions, devices, and agents — as an independently verifiable signed receipt. Unlike a snapshot credential, a receipt must be regenerated by a live, present entity — raising the cost of replay and copying.",
          },
          {
            question: "Can AI agents use MyShape Protocol?",
            answer:
              "Yes. MyShape is designed for the Agent Economy where human and AI identities coexist. AI agents can participate as entities holding their own keys, without a separate registration protocol. However, maintaining a convincing continuous presence over time requires sustained physical interaction — raising the cost of prolonged impersonation; not established as infeasible.",
          },
        ]}
      />
      {/* Speakable — voice search eligibility for Google Assistant / Alexa */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "@id": "https://www.myshape.com/#webpage",
            url: "https://www.myshape.com",
            speakable: {
              "@type": "SpeakableSpecification",
              cssSelector: ["h1", ".hero-demo-tagline"],
            },
          }),
        }}
      />
      <HomeClient />
    </>
  );
}
