// ═══════════════════════════════════════════════════════════════════
// CPS-0002 Conformance Test Suite (Prototype)
//
// Any implementation claiming CPS-0002 Human Signal Assertion
// compatibility MUST pass these tests.
// Zero dependencies on MyShape application code — only protocol
// utilities and @noble/* libraries.
//
// Run: npx vitest run continuity-protocol/conformance/cps0002-conformance.test.ts
// ═══════════════════════════════════════════════════════════════════

import { describe, it, expect } from "vitest";

import {
  verifyAssertion,
  verifySchema,
  verifySignature,
  verifyPayloadDigest,
  verifyReceiptReference,
  verifyFreshness,
  computeReceiptHash,
  buildCanonicalAssertionPayload,
  type CPS0002Assertion,
  type CPS0001Receipt,
  type CPS0002VerificationResult,
} from "../cps-0002-toy-attester/verifier";

import {
  verifyAssertion as verifyWithSecond,
  verifyPayloadDigest as secondVerifyPayloadDigest,
} from "../cps-0002-second-verifier/verifier";

import {
  buildAssertion,
  computePayloadDigest,
  deriveKeyPair,
  buildDeterministicAssertion,
  toyEvidence,
} from "../cps-0002-toy-attester/src/index";

import { canonicalSerialize } from "../shared/jcs";
import { sha256 } from "@noble/hashes/sha2.js";
import { bytesToHex } from "@noble/hashes/utils.js";
import { ed25519 } from "@noble/curves/ed25519.js";

const sha256Hex = (s: string) => bytesToHex(sha256(new TextEncoder().encode(s)));

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

// Test vector (generated by scripts/gen-cps0002-test-vector.mjs)
import assertion01 from "../test-vectors/cps0002/human-signal-01.json";
import receipt01 from "../test-vectors/valid/single-engine.json";
import receipt02 from "../test-vectors/valid/multi-engine.json";

// Fixed attester key (same as gen-cps0002-test-vector.mjs)
const ATTESTER_SECRET =
  "37e91b18c7b9d3a6f8e4c2b1a0d9f8e7c6b5a4d3e2f1a0b9c8d7e6f5a4b3c2d1";
const FUTURE_DATE = "2099-12-31T23:59:59.000Z";
const PAST_DATE = "2000-01-01T00:00:00.000Z";

function clone<T>(obj: T): T {
  return JSON.parse(JSON.stringify(obj)) as T;
}

// ═══════════════════════════════════════════
// POSITIVE TESTS
// ═══════════════════════════════════════════

describe("CONFORMANCE-01: valid assertion — schema (V0)", () => {
  it("✓ passes schema validation", () => {
    expect(verifySchema(assertion01 as unknown as CPS0002Assertion)).toBeNull();
  });

  it("✓ has correct protocolType", () => {
    expect((assertion01 as unknown as CPS0002Assertion).protocolType).toBe("cps-hsa-0.1-draft");
  });
});

describe("CONFORMANCE-02: valid assertion — canonical payload (V1)", () => {
  it("✓ payload is reconstructable and deterministic", () => {
    const a = clone(assertion01 as unknown as CPS0002Assertion);
    const payload1 = buildCanonicalAssertionPayload(a);
    const payload2 = buildCanonicalAssertionPayload(clone(a));
    expect(payload1).toBe(payload2);
  });

  it("✓ payload matches the documented 12-field canonical format", () => {
    const a = clone(assertion01 as unknown as CPS0002Assertion);
    const payload = buildCanonicalAssertionPayload(a);
    // Reconstruct the expected payload from the assertion's own fields.
    // Sub-fields (subject.id "sha256:...", ISO timestamps) contain colons,
    // so splitting on ":" is NOT a valid way to count fields.
    const expected = [
      a.protocolType,
      a.assertionId,
      a.attester.id,
      a.attester.publicKey,
      a.subject.id,
      a.reference.receiptHash,
      a.reference.receiptId,
      a.evidence.engineId,
      a.evidence.payloadDigest,
      a.validity.issuedAt,
      a.validity.expiresAt,
      a.signature.signedAt,
    ].join(":");
    expect(payload).toBe(expected);
  });
});

describe("CONFORMANCE-03: valid assertion — signature (V2)", () => {
  it("✓ passes Ed25519 signature verification", () => {
    expect(verifySignature(assertion01 as unknown as CPS0002Assertion)).toBeNull();
  });
});

describe("CONFORMANCE-04: valid assertion — receipt reference (V3)", () => {
  it("✓ receipt hash matches", () => {
    expect(
      verifyReceiptReference(
        assertion01 as unknown as CPS0002Assertion,
        clone(receipt01) as unknown as CPS0001Receipt,
      ),
    ).toBeNull();
  });

  it("✓ receiptId matches", () => {
    const a = clone(assertion01 as unknown as CPS0002Assertion);
    const r = clone(receipt01) as unknown as CPS0001Receipt;
    expect(a.reference.receiptId).toBe(r.receiptId);
  });

  it("✓ subject.id matches", () => {
    const a = clone(assertion01 as unknown as CPS0002Assertion);
    const r = clone(receipt01) as unknown as CPS0001Receipt;
    expect(a.subject.id).toBe(r.subject.id);
  });
});

describe("CONFORMANCE-05: valid assertion — freshness (V4)", () => {
  it("✓ not expired", () => {
    expect(verifyFreshness(assertion01 as unknown as CPS0002Assertion)).toBeNull();
  });
});

describe("CONFORMANCE-06: full verification — complete assertion verifies", () => {
  it("✓ verifyAssertion returns VALID", () => {
    const result = verifyAssertion(
      clone(assertion01) as unknown as CPS0002Assertion,
      clone(receipt01) as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("VALID");
  });
});

describe("CONFORMANCE-07: receipt hash binding — CPS-0001 → CPS-0002", () => {
  it("✓ computeReceiptHash(receipt) === assertion.reference.receiptHash", () => {
    const r = clone(receipt01) as unknown as CPS0001Receipt;
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    const computedHash = computeReceiptHash(r);
    expect(computedHash).toBe(a.reference.receiptHash);
  });

  it("✓ hash is SHA-256 of JCS canonicalization (64 hex chars)", () => {
    const r = clone(receipt01) as unknown as CPS0001Receipt;
    const hash = computeReceiptHash(r);
    expect(hash).toMatch(/^([0-9a-f]{2}){32}$/);
    expect(hash.length).toBe(64);
  });

    it("✓ does not modify the CPS-0001 receipt", () => {
    const r1 = clone(receipt01) as unknown as CPS0001Receipt;
    const r2 = clone(receipt01) as unknown as CPS0001Receipt;
    const before = JSON.stringify(r1);
    computeReceiptHash(r2);
    // r1 should be unchanged (no side effects)
    expect(JSON.stringify(r1)).toBe(before);
  });
});

// ═══════════════════════════════════════════
// NEGATIVE TESTS — TAMPER DETECTION
// ═══════════════════════════════════════════

describe("CONFORMANCE-08: modified assertion field → signature failure", () => {
  it("✗ changing assertionId → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as Record<string, unknown>).assertionId = "00000000-0000-7000-8000-000000000000";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });

  it("✗ changing subject.id → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { subject: { id: string } }).subject.id = "sha256:FAKE-SUBJECT";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });
});

describe("CONFORMANCE-09: modified receipt hash → signature failure", () => {
  it("✗ changing reference.receiptHash → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { reference: { receiptHash: string } }).reference.receiptHash =
      "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });
});

describe("CONFORMANCE-10: modified signature → failure", () => {
  it("✗ changing signature.value → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { signature: { value: string } }).signature.value =
      a.signature.value.slice(0, -2) + "00";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });
});

describe("CONFORMANCE-11: modified attester identity → failure", () => {
  it("✗ changing attester.publicKey → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { attester: { publicKey: string } }).attester.publicKey =
      "0".repeat(64);
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });

  it("✗ changing attester.id → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { attester: { id: string } }).attester.id = "FAKE-ATTISTER-ID";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });
});

describe("CONFORMANCE-12: modified validity field → signature failure", () => {
  it("✗ changing validity.expiresAt → INVALID_SIGNATURE", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    (a as { validity: { expiresAt: string } }).validity.expiresAt = "2099-01-01T00:00:00.000Z";
    const result = verifyAssertion(a, clone(receipt01) as unknown as CPS0001Receipt);
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_SIGNATURE");
    }
  });
});

// ═══════════════════════════════════════════
// ADDITIONAL NEGATIVE TESTS
// ═══════════════════════════════════════════

describe("CONFORMANCE-13: expired assertion → EXPIRED", () => {
  it("✗ assertion with past expiry fails freshness", () => {
    const attester = deriveKeyPair(ATTESTER_SECRET);
    const expired = buildAssertion({
      receipt: clone(receipt01) as unknown as import("../cps-0002-toy-attester/src/index").CPS0001Receipt,
      attester,
      issuedAt: PAST_DATE,
      expiresAt: PAST_DATE,
      evidence: toyEvidence({ challenge: "cps-0002-toy-expired" }),
      assertionSeed: "cps-0002-expired-test",
    });

    expect(verifySchema(expired as unknown as CPS0002Assertion)).toBeNull();
    expect(verifySignature(expired as unknown as CPS0002Assertion)).toBeNull();

    const freshErr = verifyFreshness(expired as unknown as CPS0002Assertion);
    expect(freshErr).toBe("EXPIRED");

    const result = verifyAssertion(
      expired as unknown as CPS0002Assertion,
      clone(receipt01) as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("EXPIRED");
    }
  });
});

describe("CONFORMANCE-14: malformed schema — wrong protocolType", () => {
  it("✗ wrong protocolType → INVALID_PROTOCOL_TYPE", () => {
    expect(verifySchema({ ...(assertion01 as object), protocolType: "wrong" } as unknown as CPS0002Assertion))
      .toBe("INVALID_PROTOCOL_TYPE");
  });
});

describe("CONFORMANCE-15: malformed schema — missing required field", () => {
  it("✗ missing attester → INVALID_SCHEMA", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    delete (a as Record<string, unknown>).attester;
    expect(verifySchema(a)).toBe("INVALID_SCHEMA");
  });

  it("✗ missing signature → INVALID_SCHEMA", () => {
    const a = clone(assertion01) as unknown as CPS0002Assertion;
    delete (a as Record<string, unknown>).signature;
    expect(verifySchema(a)).toBe("INVALID_SCHEMA");
  });
});

describe("CONFORMANCE-16: wrong referenced receipt → failure", () => {
  it("✗ valid assertion + receipt with same receiptId but altered content → INVALID_RECEIPT_HASH", () => {
    // Same receiptId and subject.id as the vector's reference, but the
    // receipt content differs → different SHA-256(JCS(receipt)) hash.
    const wrong = clone(receipt01) as Record<string, unknown>;
    // mutation that does NOT change receiptId or subject.id, but changes
    // the canonical hash of the receipt
    wrong.protocolVersion = "9.9";
    const result = verifyAssertion(
      clone(assertion01) as unknown as CPS0002Assertion,
      wrong as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_RECEIPT_HASH");
    }
  });

  it("✗ valid assertion + completely different receipt → INVALID_RECEIPT_REFERENCE", () => {
    // Different receiptId → reference mismatch detected before hash check
    const result = verifyAssertion(
      clone(assertion01) as unknown as CPS0002Assertion,
      clone(receipt02) as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("INVALID");
    if (result.status === "INVALID") {
      expect(result.reason).toBe("INVALID_RECEIPT_REFERENCE");
    }
  });
});

// ═══════════════════════════════════════════
// CROSS-IMPLEMENTATION TESTS
// ═══════════════════════════════════════════

describe("CONFORMANCE-17: cross-implementation — TS toy attester + TS verifier", () => {
  it("✓ assertion built by toy attester is verified by reference verifier", () => {
    const attester = deriveKeyPair(ATTESTER_SECRET);
    const issuedAt = "2099-01-01T00:00:00.000Z";
    const assertion = buildAssertion({
      receipt: clone(receipt01) as unknown as import("../cps-0002-toy-attester/src/index").CPS0001Receipt,
      attester,
      evidence: toyEvidence({ challenge: "cps-0002-interop-test" }),
      assertionSeed: "cps-0002-interop-test",
      issuedAt,
      expiresAt: "2099-01-01T01:00:00.000Z",
      signedAtOverride: issuedAt,
    });
    const result = verifyAssertion(
      assertion as unknown as CPS0002Assertion,
      clone(receipt01) as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("VALID");
  });
});

// ═══════════════════════════════════════════
// P1-2: CANONICAL SIGNING INPUT — BYTE DETERMINISM
// ═══════════════════════════════════════════

describe("CONFORMANCE-20: canonical signing input — byte determinism (P1-2)", () => {
  const a = clone(assertion01) as unknown as CPS0002Assertion;

  // Hardcoded expected 12 fields (extracted from human-signal-01.json),
  // used as an independent oracle — NOT derived from the implementation.
  // These are the protocol-fixed field values in protocol-fixed order.
  const expectedFields: string[] = [
    "cps-hsa-0.1-draft",
    "6fdceb85-30c0-7b90-8b2f-5594a455a369",
    "d25fc5f2bba3df7e",
    "c768f9a2ade9d12927abb1e576e0f1fffeb2eab89e6a75b5a9b357425868b215",
    "sha256:abcd1234efgh567890ijklmnopqrstuv",
    "55c4110f5a8fba68ee944bb49311f77048a358e08bb43d01be3e8ffc9414c5cc",
    "0193a62e-7b11-74a8-9c3d-f1e2a3b4c5d6",
    "TOY-HSA-999",
    // Field #9 — updated by BATCH-0002-3-F8 (F7 fix): payloadDigest is now
    // SHA-256(UTF8(JCS(evidence.payload))) instead of
    // SHA-256(JSON.stringify(evidence.payload)). Field structure/order and
    // all other field values are UNCHANGED.
    "61e3a02b6c71c1268a8fb16c9c670dea4d2640833f8e9f4f016f2ab53539c8c9",
    "2026-08-29T00:00:00.000Z",
    "2099-12-31T23:59:59.000Z",
    "2026-08-29T00:00:00.000Z",
  ];

  it("✓ field count is exactly 12", () => {
    expect(expectedFields.length).toBe(12);
  });

  it("✓ canonical payload equals the fixed expected string (byte-for-byte)", () => {
    const payload = buildCanonicalAssertionPayload(a);
    const expected = expectedFields.join(":");
    expect(payload).toBe(expected);
    // UTF-8 byte equality (same JS string => identical UTF-8 bytes)
    const payloadBytes = new TextEncoder().encode(payload);
    const expectedBytes = new TextEncoder().encode(expected);
    expect(payloadBytes.length).toBe(expectedBytes.length);
  });

  it("✓ field order is fixed (independent assembly, no split/rejoin of payload)", () => {
    const payload = buildCanonicalAssertionPayload(a);
    // Independently assemble the expected string from the hardcoded 12
    // literals — never by splitting/rejoining the produced payload.
    let acc = expectedFields[0];
    for (let i = 1; i < expectedFields.length; i++) {
      acc += ":" + expectedFields[i];
    }
    expect(acc).toBe(expectedFields.join(":"));
    expect(payload).toBe(acc);
  });

  it("✓ separator is exactly ':' (0x3A)", () => {
    const payload = buildCanonicalAssertionPayload(a);
    const expected = expectedFields.join(":");
    expect(payload).toBe(expected);
    // Each interior separator is a single ':' — asserted by the equality
    // against the hardcoded expected string.
  });

  it("✓ field #9 (index 8) IS evidence.payloadDigest; payload NOT in signing input (BATCH-0002-3-F8 regression)", () => {
    expect(expectedFields.length).toBe(12);
    // payloadDigest IS field #9:
    expect(expectedFields[8]).toBe(a.evidence.payloadDigest);
    // evidence.payload itself must NOT enter the signing input — neither its
    // JCS serialization nor any of its literal content:
    const payload = buildCanonicalAssertionPayload(a);
    expect(payload).not.toContain(canonicalSerialize(a.evidence.payload));
    expect(payload).not.toContain("This evidence contains no biometric");
  });

  it("✓ excluded fields do NOT enter the signing input", () => {
    const payload = buildCanonicalAssertionPayload(a);
    expect(payload).not.toContain("embodied"); // subject.type
    expect(payload).not.toContain("NOT PROOF OF HUMAN"); // evidence.payload content
    expect(payload).not.toContain('"confidence"'); // evidence.confidence
    expect(payload).not.toContain("TOY / PROTOTYPE"); // evidence.payload label
    expect(payload).not.toContain("0.1-draft\""); // payload.version (only protocolType has it)
  });
});

describe("CONFORMANCE-18: cross-implementation — mjs script + TS verifier", () => {
  it("✓ test vector generated by mjs script passes TS reference verifier", () => {
    const result = verifyAssertion(
      clone(assertion01) as unknown as CPS0002Assertion,
      clone(receipt01) as unknown as CPS0001Receipt,
    );
    expect(result.status).toBe("VALID");
  });
});

// ═══════════════════════════════════════════
// CPS-0001 REGRESSION TESTS
// ═══════════════════════════════════════════

describe("CONFORMANCE-19: CPS-0001 regression — receipt unmodified", () => {
  it("✓ CPS-0001 receipt hash is deterministic and matches", () => {
    const r = clone(receipt01) as unknown as CPS0001Receipt;
    const h1 = computeReceiptHash(r);
    const h2 = computeReceiptHash(clone(r) as unknown as CPS0001Receipt);
    expect(h1).toBe(h2);
  });

  it("✓ toy attester does not modify the CPS-0001 receipt", () => {
    const r1 = clone(receipt01) as unknown as CPS0001Receipt;
    const r1Before = JSON.stringify(r1);
    const attester = deriveKeyPair(ATTESTER_SECRET);
    buildAssertion({
      receipt: clone(r1) as unknown as import("../cps-0002-toy-attester/src/index").CPS0001Receipt,
      attester,
      evidence: toyEvidence(),
      assertionSeed: "cps-0002-regression",
      issuedAt: "2026-08-29T00:00:00.000Z",
    });
    expect(JSON.stringify(r1)).toBe(r1Before);
  });
});

// ═══════════════════════════════════════════
// BATCH-0002-3-F8: PAYLOAD DIGEST INTEGRITY (F7 FIX)
// T1–T8 — normative since BATCH-0002-3-F8
// ═══════════════════════════════════════════

describe("CONFORMANCE-21: payload digest integrity (F7 fix, T1–T8)", () => {
  const a01 = clone(assertion01) as unknown as CPS0002Assertion;
  const receipt = clone(receipt01) as unknown as CPS0001Receipt;
  const NOW = Date.parse("2026-08-30T00:00:00.000Z");

  function resign(a: CPS0002Assertion): CPS0002Assertion {
    const payload = buildCanonicalAssertionPayload(a);
    const sig = ed25519.sign(
      new TextEncoder().encode(payload),
      hexToBytes(ATTESTER_SECRET),
    );
    a.signature.value = bytesToHex(sig);
    return a;
  }

  // T1 — valid payload + valid JCS digest → VALID
  it("T1: valid payload + valid JCS digest → VALID (both verifiers)", () => {
    const ref = verifyAssertion(clone(a01), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a01), clone(receipt), NOW);
    expect(ref.status).toBe("VALID");
    expect(sec.status).toBe("VALID");
  });

  // T2 — modify evidence.payload only → INVALID_PAYLOAD_DIGEST
  it("T2: modified payload + unchanged digest → INVALID_PAYLOAD_DIGEST (both)", () => {
    const a = clone(a01);
    (a.evidence.payload as Record<string, unknown>).note = "MUTATED-BY-F8-T2";
    const ref = verifyAssertion(clone(a), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a), clone(receipt), NOW);
    expect(ref.status).toBe("INVALID");
    expect(ref.reason).toBe("INVALID_PAYLOAD_DIGEST");
    expect(sec.status).toBe("INVALID");
    expect(sec.reason).toBe("INVALID_PAYLOAD_DIGEST");
    // Direct step-level check (V2.5 isolated):
    expect(verifyPayloadDigest(a)).toBe("INVALID_PAYLOAD_DIGEST");
    expect(secondVerifyPayloadDigest(a)).toBe("INVALID_PAYLOAD_DIGEST");
  });

  // T3 — modify payload + recompute digest + keep old signature → INVALID_SIGNATURE
  it("T3: modified payload + recomputed digest + old signature → INVALID_SIGNATURE (both)", () => {
    const a = clone(a01);
    (a.evidence.payload as Record<string, unknown>).note = "MUTATED-BY-F8-T3";
    a.evidence.payloadDigest = sha256Hex(canonicalSerialize(a.evidence.payload));
    // The digest now matches the mutated payload → V2.5 would pass;
    // the ordered pipeline must fail at V2 first (stale signature).
    expect(verifyPayloadDigest(a)).toBeNull();
    expect(secondVerifyPayloadDigest(a)).toBeNull();
    const ref = verifyAssertion(clone(a), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a), clone(receipt), NOW);
    expect(ref.status).toBe("INVALID");
    expect(ref.reason).toBe("INVALID_SIGNATURE");
    expect(sec.status).toBe("INVALID");
    expect(sec.reason).toBe("INVALID_SIGNATURE");
  });

  // T4 — modify payload + recompute digest + re-sign → VALID
  it("T4: modified payload + recomputed digest + re-signed → VALID (both)", () => {
    const a = clone(a01);
    (a.evidence.payload as Record<string, unknown>).note = "MUTATED-BY-F8-T4";
    a.evidence.payloadDigest = sha256Hex(canonicalSerialize(a.evidence.payload));
    resign(a);
    const ref = verifyAssertion(clone(a), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a), clone(receipt), NOW);
    expect(ref.status).toBe("VALID");
    expect(sec.status).toBe("VALID");
  });

  // T5 — malformed digest → INVALID_SCHEMA (V0), both verifiers
  it("T5: malformed digest ('zz') → INVALID_SCHEMA (both)", () => {
    const a = clone(a01);
    a.evidence.payloadDigest = "zz";
    expect(verifySchema(a)).toBe("INVALID_SCHEMA");
    const ref = verifyAssertion(clone(a), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a), clone(receipt), NOW);
    expect(ref.status).toBe("INVALID");
    expect(ref.reason).toBe("INVALID_SCHEMA");
    expect(sec.status).toBe("INVALID");
    expect(sec.reason).toBe("INVALID_SCHEMA");
  });

  it("T5b: prefixed digest ('sha256:<64hex>') → INVALID_SCHEMA (both)", () => {
    const a = clone(a01);
    a.evidence.payloadDigest = "sha256:" + a01.evidence.payloadDigest;
    expect(verifySchema(a)).toBe("INVALID_SCHEMA");
    const ref = verifyAssertion(clone(a), clone(receipt), NOW);
    const sec = verifyWithSecond(clone(a), clone(receipt), NOW);
    expect(ref.reason).toBe("INVALID_SCHEMA");
    expect(sec.reason).toBe("INVALID_SCHEMA");
  });

  // T6 — both verifiers identical status + reason across all digest cases
  it("T6: both verifiers agree on status+reason for every digest case", () => {
    const cases: CPS0002Assertion[] = [];
    const t2 = clone(a01);
    (t2.evidence.payload as Record<string, unknown>).note = "MUTATED-BY-F8-T6A";
    cases.push(t2);
    const t3 = clone(a01);
    (t3.evidence.payload as Record<string, unknown>).note = "MUTATED-BY-F8-T6B";
    t3.evidence.payloadDigest = sha256Hex(canonicalSerialize(t3.evidence.payload));
    cases.push(t3);
    const t5 = clone(a01);
    t5.evidence.payloadDigest = "zz";
    cases.push(t5);
    const t5b = clone(a01);
    t5b.evidence.payloadDigest = "sha256:" + a01.evidence.payloadDigest;
    cases.push(t5b);
    cases.push(clone(a01)); // valid baseline
    for (const c of cases) {
      const ref = verifyAssertion(clone(c), clone(receipt), NOW);
      const sec = verifyWithSecond(clone(c), clone(receipt), NOW);
      expect(sec.status).toBe(ref.status);
      if (ref.status === "INVALID") {
        expect(sec.status).toBe("INVALID");
        expect((sec as { reason: string }).reason).toBe(ref.reason);
      }
    }
  });

  // T7 — producer digest == reference recomputation == second recomputation
  it("T7: producer digest == reference recomputation == second recomputation", () => {
    const producerDigest = computePayloadDigest(a01.evidence.payload);
    const viaSharedJcs = sha256Hex(canonicalSerialize(a01.evidence.payload));
    expect(producerDigest).toBe(a01.evidence.payloadDigest);
    expect(viaSharedJcs).toBe(a01.evidence.payloadDigest);
    expect(verifyPayloadDigest(a01)).toBeNull();
    expect(secondVerifyPayloadDigest(a01)).toBeNull();
  });

  // T8 — cross-language JCS fixture verification (F8-H1 / F8-M2).
  // The PYTHON_FIXTURE_JCS and PYTHON_FIXTURE_DIGEST constants below were
  // computed OUTSIDE the repository by an independent minimal RFC 8785
  // implementation in Python 3 (probe script: %TEMP%\f9-jcs-probe.py — NOT in
  // the repo, no runtime Python dependency added to the project).
  //
  // IMPORTANT: this test does NOT use Python json.dumps (which would produce
  // 1e-07 and 1.0 instead of the ES6/JCS 1e-7 and 1). The probe implements
  // RFC 8785 canonicalization with ECMAScript Number::toString semantics.
  //
  // The test verifies that JS canonicalSerialize output matches the
  // independently computed Python JCS output byte-for-byte, AND that the
  // SHA-256 digests agree.
  //
  // SCOPE (Route B): this establishes byte-compatibility between MyShape
  // canonical JSON and RFC 8785 for I-JSON-CONFORMANT input only. It is NOT
  // an RFC 8785 conformance claim: the serialization is a serializer, not a
  // validator. The non-I-JSON boundary is pinned separately in
  // "CONFORMANCE-22: canonical JSON compatibility boundary".
  it("T8: canonical JSON bytes and digest match an independent Python RFC 8785 computation (F8-H1)", () => {
    const FIXTURE: Record<string, unknown> = {
      arr: [1, "two", null, true, -0.5],
      ctrl: "\u0001\u001f",
      emoji: "\u{1F600}",
      nbsp: "\u00a0",
      neg: -0.5,
      nested: { z: 1, a: { m: true, n: null } },
      quote: 'say "hi" and a\\b',
      ratio: 1.0,
      score: 1e-7,
      whole: 42,
    };
    const PYTHON_FIXTURE_JCS =
      '{"arr":[1,"two",null,true,-0.5],"ctrl":"\\u0001\\u001f","emoji":"\u{1F600}","nbsp":"\u00a0","neg":-0.5,"nested":{"a":{"m":true,"n":null},"z":1},"quote":"say \\"hi\\" and a\\\\b","ratio":1,"score":1e-7,"whole":42}';
    const PYTHON_FIXTURE_DIGEST =
      "5915ae680e77411541658173e014d829851e502ce3adb4086d17ba031e447d51";
    expect(canonicalSerialize(FIXTURE)).toBe(PYTHON_FIXTURE_JCS);
    expect(sha256Hex(canonicalSerialize(FIXTURE))).toBe(PYTHON_FIXTURE_DIGEST);
    // Real vector payload — Python-computed digest must equal the
    // regenerated vector's payloadDigest (T7 cross-check):
    const PYTHON_REAL_DIGEST =
      "61e3a02b6c71c1268a8fb16c9c670dea4d2640833f8e9f4f016f2ab53539c8c9";
    expect(sha256Hex(canonicalSerialize(a01.evidence.payload))).toBe(
      PYTHON_REAL_DIGEST,
    );
    // Serialization hazards pinned (language-neutral JCS contract):
    expect(canonicalSerialize({ score: 1e-7 })).toBe('{"score":1e-7}');
    expect(canonicalSerialize({ score: 1.0 })).toBe('{"score":1}');
    // JCS sorts keys — insertion order is irrelevant:
    expect(canonicalSerialize({ b: 1, a: 2 })).toBe('{"a":2,"b":1}');
  });
});

// ═══════════════════════════════════════════
// CONFORMANCE-22: Canonical JSON compatibility boundary (Route B)
//
// Pins the documented boundary as TESTED behavior. MyShape canonical JSON is
// byte-compatible with RFC 8785 (JCS) for I-JSON-conformant input, but it is
// a serializer, not a validator: it does NOT reject the inputs RFC 8785
// requires an error for.
//
// These tests exist so the boundary cannot drift silently. If the primitive
// is ever hardened to reject (Route A), these assertions must be updated
// deliberately rather than discovered by accident.
//
// Normative: CPS-0002-VERIFIER-CONTRACT.md §5.0; CPS-0002-TRUST-POLICY.md §12-D.
// No serialization behavior is changed by this suite — it only pins it.
// ═══════════════════════════════════════════

describe("CONFORMANCE-22: canonical JSON compatibility boundary (Route B)", () => {
  it("non-finite numbers serialize as null (RFC 8785 requires rejection)", () => {
    expect(canonicalSerialize({ n: NaN })).toBe('{"n":null}');
    expect(canonicalSerialize({ n: Infinity })).toBe('{"n":null}');
    expect(canonicalSerialize({ n: -Infinity })).toBe('{"n":null}');
  });

  it("non-finite numbers do not throw", () => {
    expect(() => canonicalSerialize({ n: NaN })).not.toThrow();
    expect(() => canonicalSerialize({ n: Infinity })).not.toThrow();
  });

  it("non-finite numbers are NOT reachable from JSON text", () => {
    // JSON.parse cannot produce NaN/Infinity — they arise only in-process.
    expect(() => JSON.parse("NaN")).toThrow();
    expect(() => JSON.parse("Infinity")).toThrow();
    expect(JSON.parse('{"n":null}').n).toBeNull();
  });

  it("a lone surrogate serializes as a \\uXXXX escape (RFC 8785 requires rejection)", () => {
    expect(canonicalSerialize({ s: "\ud800" })).toBe('{"s":"\\ud800"}');
    expect(() => canonicalSerialize({ s: "\ud800" })).not.toThrow();
  });

  it("a lone surrogate IS reachable from JSON text (unlike NaN / undefined)", () => {
    const parsed = JSON.parse('{"s":"\\ud800"}');
    // unpaired high surrogate — parses successfully
    expect(parsed.s.charCodeAt(0)).toBe(0xd800);
    expect(() => canonicalSerialize(parsed)).not.toThrow();
    // self-consistent: same input → same bytes
    expect(canonicalSerialize(parsed)).toBe(
      canonicalSerialize(JSON.parse('{"s":"\\ud800"}')),
    );
  });

  it("undefined members are omitted; undefined array elements become null", () => {
    expect(canonicalSerialize({ a: 1, b: undefined })).toBe('{"a":1}');
    expect(canonicalSerialize({ a: undefined })).toBe("{}");
    expect(canonicalSerialize([1, undefined, 2])).toBe("[1,null,2]");
  });

  it("conformant input matches the RFC 8785 rules (the compatible side)", () => {
    // The same rules T8 verifies against the independent Python computation.
    expect(canonicalSerialize({ n: 1.0 })).toBe('{"n":1}');
    expect(canonicalSerialize({ n: 1e-7 })).toBe('{"n":1e-7}');
    expect(canonicalSerialize({ n: 1e-6 })).toBe('{"n":0.000001}');
    expect(canonicalSerialize({ n: 1e21 })).toBe('{"n":1e+21}');
    expect(canonicalSerialize({ n: -0 })).toBe('{"n":0}');
    expect(canonicalSerialize({ b: 1, a: 2 })).toBe('{"a":2,"b":1}');
    // U+007F, U+2028, U+2029 are NOT escaped (RFC 8785 §3.2.2.2)
    expect(canonicalSerialize({ s: "\u007F" })).toBe('{"s":"\u007F"}');
    expect(canonicalSerialize({ s: "\u2028" })).toBe('{"s":"\u2028"}');
  });
});


